export const images = {
  logo: "/assets/logo.png",
  productsHero: "/assets/site-06.jpg",
  roofTile: "/assets/bct-05.jpg",
  floorTile: "/assets/floor-red.jpg",
  jaaliProduct: "/assets/jaali-edan.jpg",
  brickProduct: "/assets/wall-wirecut.jpg",
  aboutHero: "/assets/site-04.jpg",
  story: "/assets/site-02.jpg",
  map: "/assets/site-06.jpg",
  projectHome: "/assets/site-06.jpg",
  projectJaali: "/assets/site-01.jpg",
  projectWall: "/assets/project-06.jpg",
  villa: "/assets/site-03.jpg",
  appHero: "/assets/site-03.jpg",
  basin: "/assets/floor-red.jpg",
  indoor: "/assets/site-03.jpg",
  outdoor: "/assets/project-04.jpg",
  screen: "/assets/site-02.jpg",
};
